### ISSUE TITLE
Upgrade the docker image to the latest

### ISSUE THREAD

**Issue by robertoperuzzo** [kevinquillen/ddev-typesense#5]
Upgrade the Typesense Docker image from 0.25.1 to 28.0.

Looking at Typesense [documentation](https://typesense.org/docs/guide/install-typesense.html#docker-compose) we have to use this snippet

```yaml
services:
  typesense:
    image: typesense/typesense:28.0
```
